apiVersion: apps/v1
kind: Deployment
metadata:
  name: cv-image-test
  namespace: tmpgitops
  labels:
    app: cv-image-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cv-image-test
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: cv-image-test
        version: "v-bad-nginx"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: metrics
        image: nginx:1.27-alpine
        ports:
        - containerPort: 80
          name: http
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 2
          periodSeconds: 5
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            cpu: 100m
            memory: 64Mi
